config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  resources :coupon_codes
  resources :products do
    member do
      get :apply_coupon
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coupon_code.rb
class CouponCode < ApplicationRecord
  has_many :products
  validates :discount, presence: true, numericality: { greater_than: 0 }
  validates :code, uniqueness: true

  before_save :generate_code

  def is_valid_code?
    (begin_at < Time.now.beginning_of_day) && (end_at > Time.now.end_of_day)
  end

  private
  def generate_code
    if code.empty?
      self.code = SecureRandom.hex[1..8].upcase
    else
      self.code = code.upcase
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :coupon_code, optional: true
  validates :title, presence: true
  validates :price, presence: true

  def apply_coupon(coupon)
    if coupon.is_valid_code?
      self.price -= coupon.discount
      self.price = 0 if self.price <= 0
    else
      errors[:coupon_code] << "無效"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/coupon_codes_controller.rb
class CouponCodesController < ApplicationController
  before_action :set_coupon_code, only: [:show, :edit, :update, :destroy]

  def index
    @coupon_codes = CouponCode.all
  end

  def show
  end

  def new
    @coupon_code = CouponCode.new
  end

  def edit
  end

  def create
    @coupon_code = CouponCode.new(coupon_code_params)

    respond_to do |format|
      if @coupon_code.save
        format.html { redirect_to @coupon_code, notice: 'Coupon code was successfully created.' }
        format.json { render :show, status: :created, location: @coupon_code }
      else
        format.html { render :new }
        format.json { render json: @coupon_code.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @coupon_code.update(coupon_code_params)
        format.html { redirect_to @coupon_code, notice: 'Coupon code was successfully updated.' }
        format.json { render :show, status: :ok, location: @coupon_code }
      else
        format.html { render :edit }
        format.json { render json: @coupon_code.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @coupon_code.destroy
    respond_to do |format|
      format.html { redirect_to coupon_codes_url, notice: 'Coupon code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coupon_code
      @coupon_code = CouponCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coupon_code_params
      params.require(:coupon_code).permit(:code, :discount, :begin_at, :end_at, :allow_multiple_usage)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :apply_coupon]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def apply_coupon
    coupon = CouponCode.find_by(code: params[:product][:coupon_code])
    if coupon
      @product.apply_coupon(coupon)
    else
      redirect_to root_path, notice: "折價代碼無效"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coupon_codes_helper.rb
module CouponCodesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/coupon_codes/_form.html.erb
<%= simple_form_for(@coupon_code) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :code, label: false, placeholder: '折扣代碼，若無填寫則自動產生' %>
    <%= f.input :discount, label: false, placeholder: '折扣金額' %>
    <%= f.input :begin_at, label: "起始日期" %>
    <%= f.input :end_at, label: "結束日期" %>
    <%= f.input :allow_multiple_usage, label: "允許多次使用" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/coupon_codes/edit.html.erb
<h1>Editing Coupon Code</h1>

<%= render 'form', coupon_code: @coupon_code %>

<%= link_to 'Show', @coupon_code %> |
<%= link_to 'Back', coupon_codes_path %>

app/views/coupon_codes/index.html.erb
<h1>折價券</h1>

<%= link_to '新增折扣碼', new_coupon_code_path, class: 'btn btn-primary' %>

<table class="table">
  <thead>
    <tr>
      <th>代碼</th>
      <th>折扣金額</th>
      <th>有效日期</th>
      <th>可多次使用</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @coupon_codes.each do |coupon_code| %>
      <tr>
        <td><%= coupon_code.code %></td>
        <td><%= coupon_code.discount %></td>
        <td>
          <%= coupon_code.begin_at %> ~
          <%= coupon_code.end_at %>
        </td>
        <td><%= coupon_code.allow_multiple_usage %></td>
        <td>
          <%= link_to 'Edit', edit_coupon_code_path(coupon_code) %>
          <%= link_to 'Destroy', coupon_code, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/coupon_codes/new.html.erb
<h1>New Coupon Code</h1>

<%= render 'form', coupon_code: @coupon_code %>

<%= link_to 'Back', coupon_codes_path %>

app/views/coupon_codes/show.html.erb
<p>
  <strong>Code:</strong>
  <%= @coupon_code.code %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @coupon_code.discount %>
</p>

<p>
  <strong>Begin at:</strong>
  <%= @coupon_code.begin_at %>
</p>

<p>
  <strong>End at:</strong>
  <%= @coupon_code.end_at %>
</p>

<p>
  <strong>Allow multiple usage:</strong>
  <%= @coupon_code.allow_multiple_usage %>
</p>

<%= link_to 'Edit', edit_coupon_code_path(@coupon_code) %> |
<%= link_to 'Back', coupon_codes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coupon</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <p id="notice"><%= notice %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_code.html.erb
<%= simple_form_for product, method: :get, url: apply_coupon_product_path(product) do |f| %>
  <h3>使用折扣碼</h3>
  <%= f.input :coupon_code, label: false, placeholder: '請填寫折扣代碼' %>
  <%= f.submit "使用", class: 'btn btn-success' %>
<% end %>

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/apply_coupon.html.erb
<h1>
  <%= @product.title %>
</h1>

<p>
  <%= @product.description %>
</p>

<%= render 'code', product: @product %>

<p>
  <strong>售價:</strong>
  <%= @product.price %>元
</p>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>

<%= link_to '新增商品', new_product_path, class: "btn btn-primary" %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>名稱</th>
      <th>說明</th>
      <th>售價</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.title, product %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td>
          <div class="btn-group" role="group">
            <%= link_to '編輯', edit_product_path(product), class: "btn btn-success" %>
            <%= link_to '刪除', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1>
  <%= @product.title %>
</h1>

<p>
  <%= @product.description %>
</p>

<p>
  <strong>售價:</strong>
  <%= @product.price %>元
</p>

<%= render 'code', product: @product %>

<hr />
<div class="btn-group" role="group">
  <%= link_to '編輯', edit_product_path(@product), class: 'btn btn-default' %>
  <%= link_to '回上頁', products_path, class: 'btn btn-default' %>
</div>